server:
  port: 3000

spring:
  #파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB

  #정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  #데이터베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: BADUK
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: create

  #라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  #타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  #파일 설정
  file:
    url: /upload/
    path: C:/uploads/

# 파일 업로드 경로 설정
file:
  upload:
    path: C:/uploads/
    url: /uploads/

profiles:
  active: dev

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace